packages:
  - packages/x
  - packages/core
  - packages/http
  - packages/dashboard
  - packages/cli
  - packages/universal
  - packages/xiaomi
overrides:
  '@mufan/eslint-plugin': link:../../../.local/share/pnpm/global/5/node_modules/@mufan/eslint-plugin
  eslint-plugin: link:../../../.local/share/pnpm/global/5/node_modules/@mufan/eslint-plugin
publicHoistPattern:
  - '*eslint-plugin*'
